# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Determine changed directories
      id: changed_dirs
      run: echo "::set-output name=changed_dirs::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -oE '^(cuti|kelas)/' | head -n 1)"

    - name: Run tests based on changed directory
      run: |
        changed_dir="${{ steps.changed_dirs.outputs.changed_dirs }}"
        if [ "$changed_dir" = "cuti/" ]; then
          go test -v ./cuti/tests
        elif [ "$changed_dir" = "kelas/" ]; then
          go test -v ./kelas/tests
        else
          echo "No relevant tests to run."
        fi
